### ISSUE TITLE
I writing eap server

### ISSUE THREAD

**Issue by alex-eri** [sensepost/understanding-eap#1]
Hello, 

I writed RADIUS-EAP-PEAP-MSCHAPV2, but eapol_test not accepting my MPPE keys

```
EAP: EAP entering state RECEIVED
EAP: Received EAP-Success
EAP: Status notification: completion (param=success)
EAP: EAP entering state FAILURE
CTRL-EVENT-EAP-FAILURE EAP authentication failed
```
I did not find any way to debug it... Can you help me?

**Comment by cablethief** [comment]
If you are referring to https://github.com/alex-eri/uradius then you may be missing this piece:
https://github.com/sensepost/understanding-eap/blob/master/eap.py#L168

**Comment by alex-eri** [comment]
eap part not pushed to repo

**Comment by alex-eri** [comment]
My problem now is with about sm->decision (
https://github.com/CyanogenMod/android_external_wpa_supplicant_8/blob/f953a5b2685c94ec38ef0da46015522f99336db6/src/eap_peer/eap.c#L676 )

Inner `mschapv2` successed.

Then i recieved success response and I sending MPPE keys in radius attrs and phase1 eap sucess.

But supplicant entering failed state.

Thinking about EAP TLV, but cant find any information.

keys generated with


            EAP_TLS_MPPE_KEY_LEN  = 32

            salt = mschap.create_salt()

            material = sslkeylog.export_keying_material(sess.tls.sslo, 4 * EAP_TLS_MPPE_KEY_LEN, "client EAP encryption")

            recvkey = material[:EAP_TLS_MPPE_KEY_LEN]
            sendkey = material[EAP_TLS_MPPE_KEY_LEN:EAP_TLS_MPPE_KEY_LEN*2]

            sendkey = mschap.get_new_key_from_sha(sendkey, sendkey, EAP_TLS_MPPE_KEY_LEN)
            recvkey = mschap.get_new_key_from_sha(recvkey, recvkey, EAP_TLS_MPPE_KEY_LEN)

            sendkey = mschap.create_plain_text(sendkey)
            recvkey = mschap.create_plain_text(recvkey)

            sendkeye = mschap.radius_encrypt_keys(sendkey, request.secret, request.RequestAuthenticator, salt)
            recvkeye = mschap.radius_encrypt_keys(recvkey, request.secret, request.RequestAuthenticator, salt)

            response['Microsoft.MS-MPPE-Send-Key'] = salt + sendkeye
            response['Microsoft.MS-MPPE-Recv-Key'] = salt + recvkeye
